language: c
compiler:
  - clang
  - gcc
matrix:
  include:
    - compiler: gcc
      env: GCOV=1

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libevent-dev libpcap-dev libcap-ng-dev libmnl-dev 
  - sudo apt-get install -qq libpci-dev autotools-dev check pkg-config
  - sudo apt-get install -qq lsb-base pciutils
  - sudo apt-get install -qq slirp aufs-tools
  - sudo pip install cpp-coveralls
before_script:
  - autoreconf -i
script:
  - 'CHECK="check"'
  - 'if [ "$GCOV" = 1 ]; then FLAGS="$FLAGS --enable-gcov"; CHECK="check-uml"; fi'
  - './configure $FLAGS && make && make $CHECK'
after_success:
  - 'if [ "$GCOV" = 1 ]; then coveralls -b src -r src -e compat -e netif_bsd.c -E ".*\.h" --gcov-options "\-lp"; fi'
