language: c
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libevent-dev libpcap-dev libcap-ng-dev libmnl-dev 
  - sudo apt-get install -qq libpci-dev autotools-dev check pkg-config
# before build script, run autoreconf
before_script:
  - git log --no-merges > doc/ChangeLog
  - autoreconf -i
script: "./configure && make && make check"
