language: c
compiler:
  - clang
  - gcc
matrix:
  include:
    - compiler: gcc
      env: GCOV=1

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libevent-dev libpcap-dev libcap-ng-dev libmnl-dev 
  - sudo apt-get install -qq libpci-dev autotools-dev check pkg-config
  - sudo pip install cpp-coveralls
before_script:
  - git log --no-merges > doc/ChangeLog
  - autoreconf -i
script:
  - 'if [ "$GCOV" = 1 ]; then FLAGS="$FLAGS --enable-gcov"; fi'
  - './configure $FLAGS && make && make check'
after_success:
  - 'if [ "$GCOV" = 1 ]; then coveralls -b src -r src --gcov-options "\-lp"; fi'
